# Custom Language File for Launcher Customizer

[ejs.app]
title = "Magic Academy Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/MaitreCapybaraoff/Magic-Academy"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@DracoMC_off"
mediaDiscordURL = "https://discord.gg/csFphFzN9d"

[ejs.settings]
sourceGithubLink = "https://github.com/MaitreCapybaraoff/Magic-Academy"
supportLink = "https://github.com/MaitreCapybaraoff/Magic-Academy/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE sur le Magic Academy"
welcomeDescription = "La meilleur académie de Magie."
welcomeDescCTA = "Vous n'êtes qu'à quelques clics de l'académie de magie."
